# Generated by Django 2.0.1 on 2018-02-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_add_author', 'Can add author'), ('can_change_author', 'Can change author'), ('can_delete_author', 'Can delete author'))},
        ),
    ]
